// apps/catalog/src/App.tsx
import React, { useState } from 'react';
import * as DS from '@careernote/react';
import * as ExtraIcons from '@careernote/react/icons-extra';
import { iconMap } from '@careernote/react';
import tokens from '@careernote/tokens/tokens.json'
import symbol from '@careernote/assets/logo/careernote-symbol.svg'
import logoLight from '@careernote/assets/logo/careernote-logo.png'
import logoDark from '@careernote/assets/logo/careernote-logo-on-dark.png';
import Lottie from 'lottie-react';
import lottieAi from '@careernote/assets/lottie/ai.json';
import lottieCheck from '@careernote/assets/lottie/check.json';
import lottieEvaluation from '@careernote/assets/lottie/evaluation.json';
import lottieSearch from '@careernote/assets/lottie/search.json';
import lottieLoadingDots from '@careernote/assets/lottie/LoadingDots.json';

const {
  Button,
  AddDashedButton,
  IconButton,
  Icon,
  ActivityCard,
  ToggleButton,
  Chip,
  CategoryChip,
  SelectCard,
  SelectableChip,
  TextLink,
  ConfirmModal,
  PlanCard,
  PlanFeature,
  RibbonBadge,
  StarGrid,
  Badge,
  TextInput,
  Textarea,
  Selector,
  Checkbox,
  Alert,
  Modal,
  ModalHeader,
  Information,
  NumberBadge,
  Tooltip,
  ProgressBarItem,
} = DS;

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border_gray">{title}</h2>
      {children}
    </section>
  );
}

function Swatch({ name, value }: { name: string; value: string }) {
  return (
    <div className="flex flex-col gap-1">
      <div className="w-full h-16 rounded-medium border border-border_gray" style={{ background: value }} />
      <div className="text-detail font-semibold text-gray900">{name}</div>
      <div className="text-detail text-gray700 font-mono">{value}</div>
    </div>
  );
}

function ColorSection() {
  return (
    <Section title="Colors">
      {Object.entries(tokens.color).map(([group, colors]) => (
        <div key={group} className="mb-6">
          <h3 className="text-subtitle3 font-semibold text-gray800 mb-3 capitalize">{group}</h3>
          <div className="grid grid-cols-4 tablet:grid-cols-2 gap-4">
            {Object.entries(colors as Record<string, string>).map(([name, value]) => (
              <Swatch key={name} name={name} value={value} />
            ))}
          </div>
        </div>
      ))}
      <h3 className="text-subtitle3 font-semibold text-gray800 mb-3">Gradients</h3>
      <div className="grid grid-cols-2 gap-4">
        {Object.entries(tokens.gradient).map(([name, value]) => (
          <Swatch key={name} name={name} value={value} />
        ))}
      </div>
    </Section>
  );
}

function TypographySection() {
  return (
    <Section title="Typography">
      <div className="flex flex-col gap-3">
        {Object.entries(tokens.typography.fontSize).map(([name, v]) => (
          <div key={name} className="flex items-baseline gap-6">
            <span className="w-[120px] shrink-0 text-detail text-gray700 font-mono">
              {name} · {(v as { size: string }).size}
            </span>
            <span style={{ fontSize: (v as { size: string }).size, lineHeight: (v as { lineHeight: string }).lineHeight }} className="text-gray900 font-semibold truncate">
              커리어노트 디자인 시스템
            </span>
          </div>
        ))}
      </div>
    </Section>
  );
}

function SurfaceSection() {
  return (
    <Section title="Radius & Shadow">
      <div className="flex gap-4 flex-wrap mb-6">
        {Object.entries(tokens.radius).map(([name, value]) => (
          <div key={name} className="flex flex-col items-center gap-1">
            <div className="w-20 h-14 bg-sky_bg border border-sky" style={{ borderRadius: value }} />
            <span className="text-detail text-gray700">{name} · {value}</span>
          </div>
        ))}
      </div>
      <div className="grid grid-cols-4 tablet:grid-cols-2 gap-6">
        {Object.entries(tokens.shadow).map(([name, value]) => (
          <div key={name} className="flex flex-col items-center gap-2 py-4">
            <div className="w-full h-[72px] bg-white100 rounded-large" style={{ boxShadow: value }} />
            <span className="text-detail text-gray700">{name}</span>
          </div>
        ))}
      </div>
    </Section>
  );
}

const noop = () => {};

function ButtonSection() {
  const [on, setOn] = useState(true);
  const colors = ['white', 'black', 'sky', 'red', 'transparent'] as const;
  const sizes = ['sm', 'md', 'lg'] as const;
  return (
    <Section title="Buttons">
      <div className="flex flex-col gap-4">
        {sizes.map((size) => (
          <div key={size} className="flex items-center gap-3 flex-wrap">
            <span className="w-10 text-detail text-gray700 font-mono">{size}</span>
            {colors.map((color) => (
              <Button key={color} size={size} color={color} onClick={noop}>
                {color}
              </Button>
            ))}
          </div>
        ))}
        <div className="max-w-[420px]">
          <AddDashedButton onClick={() => {}} />
        </div>
        <div className="flex items-center gap-3">
          <span className="text-detail text-gray700">IconButton</span>
          <IconButton aria-label="수정" onClick={() => {}}>
            <Icon name="edit" size="md" />
          </IconButton>
          <IconButton aria-label="삭제" onClick={() => {}}>
            <Icon name="delete" size="md" />
          </IconButton>
          <IconButton aria-label="더보기" variant="ghost" onClick={() => {}}>
            <Icon name="dotmenu" size="md" />
          </IconButton>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-detail text-gray700">disabled</span>
          <Button color="sky" disabled onClick={noop}>disabled</Button>
          <span className="text-detail text-gray700 ml-6">ToggleButton</span>
          <ToggleButton checked={on} onChange={setOn} />
          <ToggleButton checked={!on} onChange={() => setOn(!on)} size="sm" />
        </div>
      </div>
      <h3 className="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">TextLink</h3>
      <div className="flex items-center gap-4"><TextLink>직접 입력하기</TextLink><TextLink>다른 직업 보기</TextLink></div>
    </Section>
  );
}

function ChipSection() {
  const colors = ['black', 'basic', 'sky', 'red', 'blue', 'green', 'purple'] as const;
  const sizes = ['S', 'M', 'L', 'XL'] as const;
  return (
    <Section title="Chips">
      {(['solid', 'soft'] as const).map((variant) => (
        <div key={variant} className="mb-4">
          <h3 className="text-subtitle3 font-semibold text-gray800 mb-2">{variant}</h3>
          {sizes.map((size) => (
            <div key={size} className="flex items-center gap-2 mb-2 flex-wrap">
              <span className="w-6 text-detail text-gray700 font-mono">{size}</span>
              {colors.map((color) => (
                <Chip key={color} size={size} color={color} variant={variant}>
                  {color}
                </Chip>
              ))}
            </div>
          ))}
        </div>
      ))}
      <h3 className="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">SelectableChip — 별(대표)+✕ 선택 칩</h3>
      <div className="flex flex-wrap gap-2">
        <SelectableChip representative starTitle="대표 직무">백엔드 개발</SelectableChip>
        <SelectableChip starTitle="대표로 지정">데이터 분석가</SelectableChip>
      </div>
      <h3 className="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">CategoryChip — 카테고리 필터 (직업 선택 플로우)</h3>
      <div className="flex flex-wrap gap-2">
        <CategoryChip active>전체</CategoryChip>
        <CategoryChip>개발</CategoryChip>
        <CategoryChip>데이터·AI</CategoryChip>
        <CategoryChip>디자인</CategoryChip>
      </div>
    </Section>
  );
}

function InputSection() {
  const [sel, setSel] = useState('');
  return (
    <Section title="Inputs">
      <div className="grid grid-cols-2 tablet:grid-cols-1 gap-6 max-w-[720px]">
        <TextInput label="라벨" sublabel="서브라벨" placeholder="텍스트를 입력하세요" essential />
        <TextInput label="에러 상태" placeholder="값" errorMessage="에러 메시지입니다" />
        <Textarea label="Textarea" placeholder="여러 줄 입력" />
        <Selector
          label="Selector"
          placeholder="선택하세요"
          value={sel}
          options={['옵션 A', '옵션 B', '옵션 C']}
          onChange={setSel}
        />
        <div>
          <p className="text-detail text-gray600 mb-2">Checkbox — 선택 체크 (24px, 순번 표시·disabled 지원)</p>
          <div className="flex items-center gap-3">
            <Checkbox />
            <Checkbox checked />
            <Checkbox checked number={2} />
            <Checkbox disabled />
            <CheckboxToggleDemo />
          </div>
        </div>
      </div>
    </Section>
  );
}

function CheckboxToggleDemo() {
  const [on, setOn] = useState(false);
  return <Checkbox checked={on} onChange={setOn} />;
}

function FeedbackSection() {
  const [alertOpen, setAlertOpen] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  return (
    <Section title="Feedback & Overlays">
      <div className="flex items-center gap-3 mb-6">
        <Button color="black" onClick={() => setAlertOpen(true)}>Alert 열기</Button>
        <Button color="sky" onClick={() => setModalOpen(true)}>Modal 열기</Button>
        <Button color="white" onClick={() => setConfirmOpen(true)}>ConfirmModal 열기</Button>
      </div>
      {alertOpen && (
        <Alert
          type="confirm"
          title="정말 진행할까요?"
          subtitle="이 동작은 되돌릴 수 있습니다."
          onCancel={() => setAlertOpen(false)}
          onAction={() => setAlertOpen(false)}
        />
      )}
      <ConfirmModal
        isOpen={confirmOpen}
        onClose={() => setConfirmOpen(false)}
        onConfirm={() => setConfirmOpen(false)}
        onDismiss={() => setConfirmOpen(false)}
        title="정말 삭제하시겠어요?"
        description="삭제하면 되돌릴 수 없습니다."
      />
      <Modal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        title="모달 제목"
        subtitle="모달 서브타이틀"
        description="모달 설명 텍스트입니다."
        primaryButton={{ label: '확인', onClick: () => setModalOpen(false) }}
        secondaryButton={{ label: '취소', onClick: () => setModalOpen(false) }}
      />
      <div className="mb-6">
        <span className="text-detail text-gray700">ModalHeader — 대형 다이얼로그 상단 (닫기 유/무)</span>
        <div className="mt-2 border border-border_gray rounded-medium overflow-hidden max-w-[720px]">
          <ModalHeader
            title="희망 직업 변경하기"
            description="지원을 원하는 직업을 모두 선택해주세요. 중복 선택할 수 있어요."
            onClose={() => {}}
          />
        </div>
        <div className="mt-3 border border-border_gray rounded-medium overflow-hidden max-w-[720px]">
          <ModalHeader title="어떤 일을 찾고 계신가요" description="닫기 버튼 없는 변형입니다." />
        </div>
      </div>
      <div className="mb-6">
        <span className="text-detail text-gray700">Lottie — @careernote/assets 정본 5종</span>
        <div className="mt-2 flex flex-wrap items-end gap-8">
          {[
            { name: 'ai', data: lottieAi },
            { name: 'check', data: lottieCheck },
            { name: 'evaluation', data: lottieEvaluation },
            { name: 'search', data: lottieSearch },
            { name: 'LoadingDots', data: lottieLoadingDots },
          ].map(l => (
            <div key={l.name} className="flex flex-col items-center gap-1">
              <Lottie animationData={l.data} loop style={{ width: 80, height: 80 }} />
              <span className="text-detail text-gray700 font-mono">{l.name}.json</span>
            </div>
          ))}
        </div>
      </div>
      <div className="flex flex-col gap-3 max-w-[560px]">
        <Information type="positive" title="긍정 안내" subtext="positive 정보 문구" />
        <Information type="negative" title="경고 안내" subtext="negative 정보 문구" />
        <Information type="normal" title="일반 안내" subtext="normal 정보 문구" />
      </div>
      <div className="flex items-center gap-6 mt-6">
        <span className="text-detail text-gray700">Badge</span>
        {(['Soon', 'New', 'Beta'] as const).map((v) => (
          <Badge key={v} variant={v} />
        ))}
        <span className="text-detail text-gray700 ml-6">NumberBadge</span>
        {[1, 2, 3].map((n) => (
          <NumberBadge key={n} number={n} />
        ))}
        <div className="relative ml-10">
          <span className="text-body2 text-gray800">Tooltip 기준 요소</span>
          <Tooltip text="툴팁 텍스트" position="top" />
        </div>
      </div>
    </Section>
  );
}

function NavigationSection() {
  return (
    <Section title="Navigation">
      <div className="flex items-center gap-6">
        <ProgressBarItem status="complete" text="완료 단계" number={1} />
        <ProgressBarItem status="editing" text="진행 중 단계" number={2} />
        <ProgressBarItem status="waiting" text="대기 단계" number={3} />
      </div>
    </Section>
  );
}

function IconSection() {
  const entries = Object.entries(iconMap) as Array<[string, React.ComponentType<{ size?: number }>]>;
  return (
    <Section title={`Icons — iconMap (${entries.length})`}>
      <p className="text-body2 text-gray700 mb-4">
        <code className="font-mono text-sky">{'<Icon name="..." />'}</code> 로 사용. 이름이 곧 API.
      </p>
      <div className="grid grid-cols-6 tablet:grid-cols-3 gap-4">
        {entries.map(([name, IconComp]) => (
          <div key={name} className="flex flex-col items-center gap-2 p-3 rounded-medium border border-border_gray2 bg-white100">
            <IconComp size={22} />
            <span className="text-detail text-gray700 text-center break-all">{name}</span>
          </div>
        ))}
      </div>
    </Section>
  );
}

function ExtraIconSection() {
  const icons = Object.entries(ExtraIcons).filter(([, v]) => typeof v === 'function') as Array<
    [string, React.ComponentType<{ className?: string }>]
  >;
  return (
    <Section title={`Icons — icons-extra (${icons.length})`}>
      <p className="text-body2 text-gray700 mb-4">
        design-system 밖 <code className="font-mono text-sky">src/icons</code> 이관분 —{' '}
        <code className="font-mono text-sky">@careernote/react/icons-extra</code>
      </p>
      <div className="grid grid-cols-6 tablet:grid-cols-3 gap-4">
        {icons.map(([name, IconComp]) => (
          <div key={name} className="flex flex-col items-center gap-2 p-3 rounded-medium border border-border_gray2 bg-white100">
            <span className="flex items-center justify-center w-6 h-6 overflow-hidden"><IconComp /></span>
            <span className="text-detail text-gray700 text-center break-all">{name}</span>
          </div>
        ))}
      </div>
    </Section>
  );
}

function CardSection() {
  return (
    <Section title="Cards (패턴)">
      <p className="text-body2 text-gray700 mb-4">
        <code className="font-mono text-sky">ActivityCard</code> — 활동 카드 껍데기 (미디어 칸 + 콘텐츠 칸,
        모바일 스택). 기능은 소비자 주입 — careernote-web ExperienceItem·career-pencil 활동 카드의 시각 정본
      </p>
      <div className="flex flex-col gap-4 max-w-[720px]">
        <ActivityCard
          media={<Icon name="image" size="lg" color="#C3C3CD" />}
          data-testid="catalog-activity-card"
        >
          <div className="flex items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Chip size="L" variant="soft" color="blue" className="font-semibold">회사 프로젝트</Chip>
              <span className="text-body2 font-medium text-gray600">2026.01 — 2026.08</span>
            </div>
            <div className="flex items-center gap-0.5">
              <IconButton aria-label="수정" onClick={() => {}}><Icon name="edit" size="md" /></IconButton>
              <IconButton aria-label="삭제" onClick={() => {}}><Icon name="delete" size="md" /></IconButton>
            </div>
          </div>
          <p className="text-subtitle2 font-semibold text-gray900 truncate">활동 제목</p>
          <p className="text-body2 text-gray700">활동 설명 텍스트가 들어갑니다.</p>
        </ActivityCard>
        <ActivityCard selected media={<Icon name="image" size="lg" color="#C3C3CD" />}>
          <p className="text-subtitle2 font-semibold text-gray900">선택된 카드 (selected)</p>
        </ActivityCard>
      </div>
      <h3 className="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">SelectCard — 체크서클 선택 카드 (직업 선택 플로우)</h3>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-[12px] max-w-[720px]">
        <SelectCard representative selected title="대표 직업">백엔드 개발</SelectCard>
        <SelectCard selected title="선택됨">데이터 분석가</SelectCard>
        <SelectCard title="기본">게임 기획자</SelectCard>
        <SelectCard title="긴 이름 말줄임">라이프스타일·뷰티·웰니스 매니저</SelectCard>
      </div>
      <h3 className="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">StarGrid — STAR 2×2 요약 (활동 카드 본문)</h3>
      <div className="max-w-[720px]">
        <StarGrid
          star={{
            situation: '업무 맥락이 정리되지 않은 초기 단계에서 단편적인 정보만 주어졌습니다.',
            task: '입력을 이력서·포트폴리오에 적합한 형태로 다듬어야 했습니다.',
            action: '핵심 의도를 파악하고 문맥상 자연스러운 배경을 보완했습니다.',
            result: '일관된 품질의 활동 소개를 빠르게 산출했습니다.',
          }}
        />
      </div>
      <h3 className="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">PlanCard + PlanFeature + RibbonBadge — 요금제 카드 (옵션 선택 플로우)</h3>
      <div className="flex flex-row items-stretch gap-[20px]">
        <PlanCard className="w-[300px]">
          <div className="flex flex-col gap-[12px] px-[12px]">
            <Chip size="L" color="black">Basic</Chip>
            <span className="text-[20px] font-bold leading-[24px] text-gray900">일반 포트폴리오</span>
            <span className="text-[16px] font-semibold leading-[20px] text-gray600">무료</span>
          </div>
          <div className="flex flex-col gap-[12px]">
            <PlanFeature emoji="📋" title="내 이력에 기반한 포트폴리오" description="AI가 내 이력을 분석해 강점을 찾아줘요." />
          </div>
        </PlanCard>
        <PlanCard selected className="w-[420px]">
          <RibbonBadge>
            <span className="text-[18px] font-semibold leading-[22px] text-white">합격률 35%</span>
          </RibbonBadge>
          <div className="flex flex-col gap-[12px] px-[12px]">
            <Chip size="L" color="sky">Fit</Chip>
            <span className="text-[20px] font-bold leading-[24px] text-gray900">선택된 카드 (selected)</span>
          </div>
          <div className="flex flex-col gap-[28px]">
            <PlanFeature layout="row" emoji="📆" title="row 레이아웃 기능 항목" description="이모지 옆에 텍스트가 배치됩니다." />
          </div>
        </PlanCard>
      </div>
    </Section>
  );
}

const SYMBOL_SIZES = [20, 24, 32, 48, 64];
const LOGO_SIZES = [22, 34, 48, 68];

function BrandSection() {
  return (
    <Section title="Brand">
      <p className="text-body2 text-gray700 mb-6">
        로고는 <code className="font-mono text-detail bg-bg_gray1 px-1 rounded-small">@careernote/assets</code> 의 파일을 그대로 씁니다.
        도형·텍스트로 다시 그리지 않고, 비율과 색은 바꾸지 않습니다.
      </p>

      <h3 className="text-subtitle3 font-semibold text-gray800 mb-3">기본 — 심볼 (아이콘 단독)</h3>
      <div className="flex flex-wrap items-end gap-8 rounded-medium border border-border_gray bg-white100 p-8 mb-2">
        {SYMBOL_SIZES.map((h) => (
          <div key={h} className="flex flex-col items-center gap-2">
            <img src={symbol} alt="CareerNote" style={{ height: h, width: h }} />
            <span className="text-detail text-gray600 font-mono">{h}px</span>
          </div>
        ))}
      </div>
      <p className="text-detail text-gray600 mb-2 font-mono">logo/careernote-symbol.svg · 1:1 · 벡터</p>
      <p className="text-body2 text-gray700 mb-6">
        이름을 함께 보여야 하는 자리에서만 아래 가로형을 씁니다.
      </p>

      <h3 className="text-subtitle3 font-semibold text-gray800 mb-3">가로형 (밝은 배경)</h3>
      <div className="rounded-medium border border-border_gray bg-white100 p-8 mb-2">
        <img src={logoLight} alt="CareerNote" className="h-[34px] w-auto" />
      </div>
      <p className="text-detail text-gray600 mb-6 font-mono">logo/careernote-logo.png · 283×34</p>

      <h3 className="text-subtitle3 font-semibold text-gray800 mb-3">가로형 (어두운 배경)</h3>
      <div className="rounded-medium bg-gray900 p-8 mb-2">
        <img src={logoDark} alt="CareerNote" className="h-[34px] w-auto" />
      </div>
      <p className="text-detail text-gray600 mb-6 font-mono">logo/careernote-logo-on-dark.png · 377×45</p>

      <h3 className="text-subtitle3 font-semibold text-gray800 mb-3">가로형 크기</h3>
      <div className="flex flex-wrap items-end gap-8 rounded-medium border border-border_gray bg-white100 p-8 mb-6">
        {LOGO_SIZES.map((h) => (
          <div key={h} className="flex flex-col items-center gap-2">
            <img src={logoLight} alt="CareerNote" style={{ height: h }} className="w-auto" />
            <span className="text-detail text-gray600 font-mono">{h}px</span>
          </div>
        ))}
      </div>

      <h3 className="text-subtitle3 font-semibold text-gray800 mb-3">사용</h3>
      <pre className="rounded-medium bg-bg_gray1 p-4 text-detail font-mono text-gray800 overflow-x-auto mb-6">
{`import symbol from '@careernote/assets/logo/careernote-symbol.svg'   // 기본
<img src={symbol} alt="CareerNote" className="size-6" />

import logo from '@careernote/assets/logo/careernote-logo.png'       // 가로형
<img src={logo} alt="CareerNote" className="h-[22px] w-auto" />

// 파일 import 가 불가능한 환경(캔버스 엔진·헤드리스)
import symbolData from '@careernote/assets/logo/careernote-symbol.base64.json'`}
      </pre>

      <h3 className="text-subtitle3 font-semibold text-gray800 mb-3">금지</h3>
      <ul className="text-body2 text-gray700 list-disc pl-5 flex flex-col gap-1">
        <li>도형·텍스트·아이콘 조합으로 로고를 다시 그리기</li>
        <li>비율 변경, 색 변경, 회전, 그림자 추가</li>
        <li>어두운 배경에 밝은 배경용 가로형을 그대로 얹기 (on-dark 파일을 쓸 것)</li>
        <li>심볼을 잘라 쓰거나 배경 사각형만 따로 쓰기</li>
      </ul>
    </Section>
  );
}

const NAV = [
  { id: 'brand', label: 'Brand', el: <BrandSection /> },
  { id: 'colors', label: 'Colors', el: <ColorSection /> },
  { id: 'typography', label: 'Typography', el: <TypographySection /> },
  { id: 'surface', label: 'Radius & Shadow', el: <SurfaceSection /> },
  { id: 'buttons', label: 'Buttons', el: <ButtonSection /> },
  { id: 'chips', label: 'Chips', el: <ChipSection /> },
  { id: 'inputs', label: 'Inputs', el: <InputSection /> },
  { id: 'feedback', label: 'Feedback & Overlays', el: <FeedbackSection /> },
  { id: 'navigation', label: 'Navigation', el: <NavigationSection /> },
  { id: 'cards', label: 'Cards', el: <CardSection /> },
  { id: 'icons', label: 'Icons', el: <IconSection /> },
  { id: 'icons-extra', label: 'Icons Extra', el: <ExtraIconSection /> },
];

export default function App() {
  const [active, setActive] = useState('brand');
  const current = NAV.find((n) => n.id === active) ?? NAV[0];
  return (
    <div className="flex min-h-screen">
      <aside className="w-60 shrink-0 border-r border-border_gray bg-white100 px-4 py-8 fixed top-0 bottom-0 left-0 overflow-y-auto">
        <h1 className="text-subtitle2 font-bold text-gray900 px-3">
          CareerNote
          <span className="block text-detail font-medium text-gray700 mt-0.5">Design System</span>
        </h1>
        <nav className="mt-6 flex flex-col gap-0.5">
          {NAV.map((item) => (
            <button
              key={item.id}
              onClick={() => setActive(item.id)}
              className={`text-left px-3 py-2 rounded-small text-body2 transition-colors ${
                active === item.id
                  ? 'bg-sky_bg text-sky font-semibold'
                  : 'text-gray800 font-medium hover:bg-bg_gray2'
              }`}
            >
              {item.label}
            </button>
          ))}
        </nav>
        <a href="./vue/" className="mt-8 mx-3 inline-block text-detail text-sky hover:underline">
          ↗ Vue 카탈로그
        </a>
        <p className="mt-2 px-3 text-detail text-gray600 leading-4">
          정본: @careernote/tokens
          <br />
          @careernote/react
        </p>
      </aside>
      <main className="ml-60 flex-1 px-10 py-10 max-w-[1080px]">{current.el}</main>
    </div>
  );
}

// apps/catalog-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  Button, ButtonRound, ToggleButton, AddDashedButton, IconButton,
  Chip, CategoryChip, SelectCard, SelectableChip, PlanCard, PlanFeature, RibbonBadge, StarGrid, Badge, NumberBadge, Tooltip, Information, ActivityCard,
  SubHeader, NextStepFooter, SearchInput, TextLink, Spinner, Checkbox, LottieLoadingDots, ConfirmModal, ResponsiveModal,
  TextInput, Textarea, Selector, Modal, InHeader, HeaderMenuItem, ProgressBarItem,
  Icon, ICON_NAME_MAP,
} from '@careernote/vue'
import tokens from '@careernote/tokens/tokens.json'
import LottiePreview from './LottiePreview.vue'
import lottieAi from '@careernote/assets/lottie/ai.json'
import lottieCheck from '@careernote/assets/lottie/check.json'
import lottieEvaluation from '@careernote/assets/lottie/evaluation.json'
import lottieSearch from '@careernote/assets/lottie/search.json'
import lottieLoadingDots from '@careernote/assets/lottie/LoadingDots.json'
import symbol from '@careernote/assets/logo/careernote-symbol.svg'
import logoLight from '@careernote/assets/logo/careernote-logo.png'
import logoDark from '@careernote/assets/logo/careernote-logo-on-dark.png'

const SYMBOL_SIZES = [20, 24, 32, 48, 64]
const LOGO_SIZES = [22, 34, 48, 68]

const NAV = [
  { id: 'brand', label: 'Brand' },
  { id: 'colors', label: 'Colors' },
  { id: 'typography', label: 'Typography' },
  { id: 'surface', label: 'Radius & Shadow' },
  { id: 'buttons', label: 'Buttons' },
  { id: 'chips', label: 'Chips' },
  { id: 'inputs', label: 'Inputs' },
  { id: 'feedback', label: 'Feedback & Overlays' },
  { id: 'navigation', label: 'Navigation' },
  { id: 'cards', label: 'Cards' },
  { id: 'icons', label: 'Icons' },
] as const

const active = ref<(typeof NAV)[number]['id']>('brand')
const toggleOn = ref(true)
const checkboxOn = ref(false)
const inputVal = ref('')
const selVal = ref('')
const modalOpen = ref(false)
const confirmOpen = ref(false)
const responsiveOpen = ref(false)
const iconNames = Object.keys(ICON_NAME_MAP)
</script>

<template>
  <div class="flex min-h-screen">
    <aside class="w-[240px] shrink-0 border-r border-border-gray bg-white100 px-4 py-8 fixed top-0 bottom-0 left-0 overflow-y-auto">
      <h1 class="text-subtitle2 font-bold text-gray900 px-3">
        CareerNote
        <span class="block text-detail font-medium text-gray700 mt-0.5">Design System · Vue</span>
      </h1>
      <nav class="mt-6 flex flex-col gap-0.5">
        <button
          v-for="item in NAV"
          :key="item.id"
          type="button"
          class="text-left px-3 py-2 rounded-small text-body2 transition-colors"
          :class="active === item.id ? 'bg-sky-bg text-sky font-semibold' : 'text-gray800 font-medium hover:bg-bg-gray2'"
          @click="active = item.id"
        >
          {{ item.label }}
        </button>
      </nav>
      <a href="../" class="mt-8 mx-3 inline-block text-detail text-sky hover:underline">↗ React 카탈로그</a>
      <a href="../guide/" class="mt-1 mx-3 inline-block text-detail text-sky hover:underline">↗ UI 작업 규칙 가이드</a>
      <p class="mt-2 px-3 text-detail text-gray600 leading-4">정본: @careernote/vue<br />(React 스펙과 클래스 동일)</p>
    </aside>

    <main class="ml-[240px] flex-1 px-10 py-10 max-w-[1080px]">
      <!-- Brand -->
      <section v-if="active === 'brand'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Brand</h2>
        <p class="text-body2 text-gray700 mb-6">
          로고는 <code class="font-mono text-detail bg-bg-gray1 px-1 rounded-small">@careernote/assets</code> 의 파일을 그대로 씁니다.
          도형·텍스트로 다시 그리지 않고, 비율과 색은 바꾸지 않습니다.
        </p>

        <h3 class="text-subtitle3 font-semibold text-gray800 mb-3">기본 — 심볼 (아이콘 단독)</h3>
        <div class="flex flex-wrap items-end gap-8 rounded-medium border border-border-gray bg-white100 p-8 mb-2">
          <div v-for="h in SYMBOL_SIZES" :key="h" class="flex flex-col items-center gap-2">
            <img :src="symbol" alt="CareerNote" :style="{ height: h + 'px', width: h + 'px' }" />
            <span class="text-detail text-gray600 font-mono">{{ h }}px</span>
          </div>
        </div>
        <p class="text-detail text-gray600 mb-2 font-mono">logo/careernote-symbol.svg · 1:1 · 벡터</p>
        <p class="text-body2 text-gray700 mb-6">이름을 함께 보여야 하는 자리에서만 아래 가로형을 씁니다.</p>

        <h3 class="text-subtitle3 font-semibold text-gray800 mb-3">가로형 (밝은 배경)</h3>
        <div class="rounded-medium border border-border-gray bg-white100 p-8 mb-2">
          <img :src="logoLight" alt="CareerNote" class="h-[34px] w-auto" />
        </div>
        <p class="text-detail text-gray600 mb-6 font-mono">logo/careernote-logo.png · 283×34</p>

        <h3 class="text-subtitle3 font-semibold text-gray800 mb-3">가로형 (어두운 배경)</h3>
        <div class="rounded-medium bg-gray900 p-8 mb-2">
          <img :src="logoDark" alt="CareerNote" class="h-[34px] w-auto" />
        </div>
        <p class="text-detail text-gray600 mb-6 font-mono">logo/careernote-logo-on-dark.png · 377×45</p>

        <h3 class="text-subtitle3 font-semibold text-gray800 mb-3">가로형 크기</h3>
        <div class="flex flex-wrap items-end gap-8 rounded-medium border border-border-gray bg-white100 p-8 mb-6">
          <div v-for="h in LOGO_SIZES" :key="h" class="flex flex-col items-center gap-2">
            <img :src="logoLight" alt="CareerNote" :style="{ height: h + 'px' }" class="w-auto" />
            <span class="text-detail text-gray600 font-mono">{{ h }}px</span>
          </div>
        </div>

        <h3 class="text-subtitle3 font-semibold text-gray800 mb-3">사용</h3>
        <pre class="rounded-medium bg-bg-gray1 p-4 text-detail font-mono text-gray800 overflow-x-auto mb-6">import symbol from '@careernote/assets/logo/careernote-symbol.svg'   // 기본
&lt;img :src="symbol" alt="CareerNote" class="size-6" /&gt;

import logo from '@careernote/assets/logo/careernote-logo.png'       // 가로형
&lt;img :src="logo" alt="CareerNote" class="h-[22px] w-auto" /&gt;

// 파일 import 가 불가능한 환경(캔버스 엔진·헤드리스)
import symbolData from '@careernote/assets/logo/careernote-symbol.base64.json'</pre>

        <h3 class="text-subtitle3 font-semibold text-gray800 mb-3">금지</h3>
        <ul class="text-body2 text-gray700 list-disc pl-5 flex flex-col gap-1">
          <li>도형·텍스트·아이콘 조합으로 로고를 다시 그리기</li>
          <li>비율 변경, 색 변경, 회전, 그림자 추가</li>
          <li>어두운 배경에 밝은 배경용 가로형을 그대로 얹기 (on-dark 파일을 쓸 것)</li>
          <li>심볼을 잘라 쓰거나 배경 사각형만 따로 쓰기</li>
        </ul>
      </section>

      <!-- Colors -->
      <section v-if="active === 'colors'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Colors</h2>
        <div v-for="(colors, group) in tokens.color" :key="group" class="mb-6">
          <h3 class="text-subtitle3 font-semibold text-gray800 mb-3 capitalize">{{ group }}</h3>
          <div class="grid grid-cols-4 gap-4">
            <div v-for="(value, name) in colors" :key="name" class="flex flex-col gap-1">
              <div class="w-full h-16 rounded-medium border border-border-gray" :style="{ background: value }" />
              <div class="text-detail font-semibold text-gray900">{{ name }}</div>
              <div class="text-detail text-gray700 font-mono">{{ value }}</div>
            </div>
          </div>
        </div>
      </section>

      <!-- Typography -->
      <section v-if="active === 'typography'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Typography</h2>
        <div class="flex flex-col gap-3">
          <div v-for="(v, name) in tokens.typography.fontSize" :key="name" class="flex items-baseline gap-6">
            <span class="w-[120px] shrink-0 text-detail text-gray700 font-mono">{{ name }} · {{ v.size }}</span>
            <span class="text-gray900 font-semibold truncate" :style="{ fontSize: v.size, lineHeight: v.lineHeight }">
              커리어노트 디자인 시스템
            </span>
          </div>
        </div>
      </section>

      <!-- Radius & Shadow -->
      <section v-if="active === 'surface'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Radius & Shadow</h2>
        <div class="flex gap-4 flex-wrap mb-6">
          <div v-for="(value, name) in tokens.radius" :key="name" class="flex flex-col items-center gap-1">
            <div class="w-20 h-14 bg-sky-bg border border-sky" :style="{ borderRadius: value }" />
            <span class="text-detail text-gray700">{{ name }} · {{ value }}</span>
          </div>
        </div>
        <div class="grid grid-cols-4 gap-6">
          <div v-for="(value, name) in tokens.shadow" :key="name" class="flex flex-col items-center gap-2 py-4">
            <div class="w-full h-[72px] bg-white100 rounded-large" :style="{ boxShadow: value }" />
            <span class="text-detail text-gray700">{{ name }}</span>
          </div>
        </div>
      </section>

      <!-- Buttons -->
      <section v-if="active === 'buttons'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Buttons</h2>
        <div v-for="size in (['sm', 'md', 'lg'] as const)" :key="size" class="flex items-center gap-3 mb-4">
          <span class="w-10 text-detail text-gray700 font-mono">{{ size }}</span>
          <Button v-for="color in (['white', 'black', 'sky', 'red'] as const)" :key="color" :size="size" :color="color">
            {{ color }}
          </Button>
        </div>
        <div class="max-w-[420px] mb-4"><AddDashedButton /></div>
        <div class="flex items-center gap-3 mb-4">
          <span class="text-detail text-gray700">IconButton</span>
          <IconButton aria-label="수정"><Icon name="edit" size="md" /></IconButton>
          <IconButton aria-label="삭제"><Icon name="delete" size="md" /></IconButton>
          <IconButton aria-label="더보기" variant="ghost"><Icon name="dotmenu" size="md" /></IconButton>
          <span class="text-detail text-gray700 ml-6">ButtonRound</span>
          <ButtonRound selected>선택됨</ButtonRound>
          <ButtonRound>기본</ButtonRound>
        </div>
        <div class="flex items-center gap-3">
          <span class="text-detail text-gray700">disabled</span>
          <Button color="sky" disabled>disabled</Button>
          <span class="text-detail text-gray700 ml-6">ToggleButton</span>
          <ToggleButton :checked="toggleOn" @change="toggleOn = $event" />
          <ToggleButton :checked="!toggleOn" size="sm" @change="toggleOn = !$event" />
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">TextLink</h3>
        <div class="flex items-center gap-4"><TextLink>직접 입력하기</TextLink><TextLink>다른 직업 보기</TextLink></div>
      </section>

      <!-- Chips -->
      <section v-if="active === 'chips'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Chips</h2>
        <div v-for="variant in (['solid', 'soft'] as const)" :key="variant" class="mb-4">
          <h3 class="text-subtitle3 font-semibold text-gray800 mb-2">{{ variant }}</h3>
          <div v-for="size in (['S', 'M', 'L', 'XL'] as const)" :key="size" class="flex items-center gap-2 mb-2 flex-wrap">
            <span class="w-6 text-detail text-gray700 font-mono">{{ size }}</span>
            <Chip
              v-for="color in (['black', 'basic', 'sky', 'red', 'blue', 'green', 'purple'] as const)"
              :key="color" :size="size" :color="color" :variant="variant"
            >
              {{ color }}
            </Chip>
          </div>
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">SelectableChip — 별(대표)+✕ 선택 칩</h3>
        <div class="flex flex-wrap gap-2">
          <SelectableChip representative star-title="대표 직무">백엔드 개발</SelectableChip>
          <SelectableChip star-title="대표로 지정">데이터 분석가</SelectableChip>
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">CategoryChip — 카테고리 필터 (pencil /make/job)</h3>
        <div class="flex flex-wrap gap-2">
          <CategoryChip active>전체</CategoryChip>
          <CategoryChip>개발</CategoryChip>
          <CategoryChip>데이터·AI</CategoryChip>
          <CategoryChip>디자인</CategoryChip>
        </div>
      </section>

      <!-- Inputs -->
      <section v-if="active === 'inputs'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Inputs</h2>
        <div class="grid grid-cols-2 gap-6 max-w-[720px]">
          <TextInput label="라벨" sublabel="서브라벨" placeholder="텍스트를 입력하세요" essential v-model="inputVal" full-width />
          <TextInput label="에러 상태" placeholder="값" state="error" error-message="에러 메시지입니다" full-width />
          <Textarea label="Textarea" placeholder="여러 줄 입력" full-width />
          <Selector label="Selector" placeholder="선택하세요" :options="['옵션 A', '옵션 B', '옵션 C']" v-model="selVal" full-width />
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">SearchInput — 돋보기+클리어</h3>
        <div class="max-w-[360px]"><SearchInput placeholder="직업 검색" /></div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">Checkbox — 선택 체크 (24px, 순번 표시·disabled 지원)</h3>
        <div class="flex items-center gap-3">
          <Checkbox /><Checkbox checked /><Checkbox checked :number="2" /><Checkbox disabled />
          <Checkbox :checked="checkboxOn" @change="v => (checkboxOn = v)" />
        </div>
      </section>

      <!-- Feedback -->
      <section v-if="active === 'feedback'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Feedback & Overlays</h2>
        <div class="flex items-center gap-3 mb-6">
          <Button color="sky" @click="modalOpen = true">Modal 열기</Button>
        <Button color="white" @click="confirmOpen = true">ConfirmModal 열기</Button>
        <Button color="black" @click="responsiveOpen = true">ResponsiveModal 열기</Button>
        </div>
        <Modal
          :is-open="modalOpen" title="모달 제목" subtitle="모달 서브타이틀" description="모달 설명 텍스트입니다."
          secondary-label="취소" @close="modalOpen = false" @primary="modalOpen = false" @secondary="modalOpen = false"
        />
        <div class="flex flex-col gap-3">
          <Information type="positive" title="긍정 안내" subtext="positive 정보 문구" />
          <Information type="negative" title="경고 안내" subtext="negative 정보 문구" />
          <Information type="normal" title="일반 안내" subtext="normal 정보 문구" />
        </div>
        <div class="flex items-center gap-6 mt-6">
          <span class="text-detail text-gray700">Badge</span>
          <Badge v-for="v in (['Soon', 'New', 'Beta'] as const)" :key="v" :variant="v" />
          <span class="text-detail text-gray700 ml-6">NumberBadge</span>
          <NumberBadge v-for="n in 3" :key="n" :number="n" />
          <div class="relative ml-10">
            <span class="text-body2 text-gray800">Tooltip 기준 요소</span>
            <Tooltip text="툴팁 텍스트" position="top" />
          </div>
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">Spinner</h3>
        <div class="flex items-center gap-8"><Spinner /><Spinner :size="20" :border="2" label="로딩 중" /></div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">Lottie — @careernote/assets 정본 5종</h3>
        <div class="flex flex-wrap items-end gap-8">
          <div v-for="l in [
            { name: 'ai', data: lottieAi },
            { name: 'check', data: lottieCheck },
            { name: 'evaluation', data: lottieEvaluation },
            { name: 'search', data: lottieSearch },
          ]" :key="l.name" class="flex flex-col items-center gap-1">
            <LottiePreview :animation-data="l.data" />
            <span class="text-detail text-gray700 font-mono">{{ l.name }}.json</span>
          </div>
          <div class="flex flex-col items-center gap-1">
            <div class="flex h-[80px] items-center"><LottieLoadingDots :animation-data="lottieLoadingDots" /></div>
            <span class="text-detail text-gray700 font-mono">LottieLoadingDots (DS 컴포넌트)</span>
          </div>
        </div>
        <ConfirmModal
          :open="confirmOpen"
          title="정말 삭제하시겠어요?"
          description="삭제하면 되돌릴 수 없습니다."
          dismissable
          @close="confirmOpen = false"
          @confirm="confirmOpen = false"
          @dismiss="confirmOpen = false"
        />
        <ResponsiveModal :open="responsiveOpen" pc-class="max-w-[480px]" @close="responsiveOpen = false">
          <div class="p-6">
            <p class="text-subtitle3 font-semibold text-gray900">ResponsiveModal</p>
            <p class="mt-2 text-body2 text-gray700">데스크톱=센터 모달 / ≤850px=하단 드로어. 창 폭을 줄여 확인하세요.</p>
          </div>
        </ResponsiveModal>
      </section>

      <!-- Navigation -->
      <section v-if="active === 'navigation'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Navigation</h2>
        <InHeader title="플로우 타이틀" description="설명 텍스트가 들어갑니다." class="mb-6" />
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-6 mb-2">SubHeader — 퍼널 스텝 헤더 (pencil)</h3>
        <div class="border border-border-gray rounded-medium overflow-hidden mb-6"><SubHeader :current-step="2" /></div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-6 mb-2">NextStepFooter — 퍼널 하단 CTA (fixed 라 캡처만 — 실제 위치는 화면 하단)</h3>
        <p class="text-body2 text-gray700 mb-2">props: mainLabel·mainDisabled·showSub·subLabel + #main-label 슬롯</p>
        <div class="flex items-center gap-8 h-14 border-b border-border-gray mb-6 px-4">
          <HeaderMenuItem label="활성 메뉴" is-active />
          <HeaderMenuItem label="기본 메뉴" />
          <HeaderMenuItem label="NEW 메뉴" show-new />
        </div>
        <div class="flex items-center gap-6">
          <ProgressBarItem status="complete" text="완료 단계" :number="1" />
          <ProgressBarItem status="editing" text="진행 중 단계" :number="2" />
          <ProgressBarItem status="waiting" text="대기 단계" :number="3" />
        </div>
      </section>

      <!-- Cards -->
      <section v-if="active === 'cards'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">Cards (패턴)</h2>
        <div class="flex flex-col gap-4 max-w-[720px]">
          <ActivityCard>
            <template #media><Icon name="image" :size="24" color="#C3C3CD" /></template>
            <div class="flex items-center justify-between gap-2">
              <div class="flex items-center gap-2">
                <Chip size="L" variant="soft" color="blue" class="font-semibold">회사 프로젝트</Chip>
                <span class="text-body2 font-medium text-gray600">2026.01 — 2026.08</span>
              </div>
              <div class="flex items-center gap-0.5">
                <IconButton aria-label="수정"><Icon name="edit" size="md" /></IconButton>
                <IconButton aria-label="삭제"><Icon name="delete" size="md" /></IconButton>
              </div>
            </div>
            <p class="text-subtitle2 font-semibold text-gray900 truncate">활동 제목</p>
            <p class="text-body2 text-gray700">활동 설명 텍스트가 들어갑니다.</p>
          </ActivityCard>
          <ActivityCard selected>
            <template #media><Icon name="image" :size="24" color="#C3C3CD" /></template>
            <p class="text-subtitle2 font-semibold text-gray900">선택된 카드 (selected)</p>
          </ActivityCard>
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">SelectCard — 체크서클 선택 카드 (pencil /make/job)</h3>
        <div class="grid grid-cols-2 sm:grid-cols-4 gap-[12px] max-w-[720px]">
          <SelectCard representative selected title="대표 직업">백엔드 개발</SelectCard>
          <SelectCard selected title="선택됨">데이터 분석가</SelectCard>
          <SelectCard title="기본">게임 기획자</SelectCard>
          <SelectCard title="긴 이름 말줄임">라이프스타일·뷰티·웰니스 매니저</SelectCard>
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">StarGrid — STAR 2×2 요약 (활동 카드 본문)</h3>
        <div class="max-w-[720px]">
          <StarGrid
            :star="{
              situation: '업무 맥락이 정리되지 않은 초기 단계에서 단편적인 정보만 주어졌습니다.',
              task: '입력을 이력서·포트폴리오에 적합한 형태로 다듬어야 했습니다.',
              action: '핵심 의도를 파악하고 문맥상 자연스러운 배경을 보완했습니다.',
              result: '일관된 품질의 활동 소개를 빠르게 산출했습니다.',
            }"
          />
        </div>
        <h3 class="text-subtitle3 font-semibold text-gray800 mt-8 mb-2">PlanCard + PlanFeature + RibbonBadge — 요금제 카드 (pencil /make/options)</h3>
        <div class="flex flex-row items-stretch gap-[20px]">
          <PlanCard class="w-[300px]">
            <div class="flex flex-col gap-[12px] px-[12px]">
              <Chip size="L" color="black">Basic</Chip>
              <span class="text-[20px] font-bold leading-[24px] text-gray900">일반 포트폴리오</span>
              <span class="text-[16px] font-semibold leading-[20px] text-gray600">무료</span>
            </div>
            <div class="flex flex-col gap-[12px]">
              <PlanFeature emoji="📋" title="내 이력에 기반한 포트폴리오" description="AI가 내 이력을 분석해 강점을 찾아줘요." />
            </div>
          </PlanCard>
          <PlanCard selected class="w-[420px]">
            <RibbonBadge>
              <span class="text-[18px] font-semibold leading-[22px] text-white">합격률 35%</span>
            </RibbonBadge>
            <div class="flex flex-col gap-[12px] px-[12px]">
              <Chip size="L" color="sky">Fit</Chip>
              <span class="text-[20px] font-bold leading-[24px] text-gray900">선택된 카드 (selected)</span>
            </div>
            <div class="flex flex-col gap-[28px]">
              <PlanFeature layout="row" emoji="📆" title="row 레이아웃 기능 항목" description="이모지 옆에 텍스트가 배치됩니다." />
            </div>
          </PlanCard>
        </div>
      </section>

      <!-- Icons -->
      <section v-if="active === 'icons'">
        <h2 class="text-title2 font-bold text-gray900 mb-6 pb-2 border-b border-border-gray">
          Icons — iconMap ({{ iconNames.length }})
        </h2>
        <p class="text-body2 text-gray700 mb-4">
          <code class="font-mono text-sky">&lt;Icon name="..." /&gt;</code> — React iconMap 과 동일 키
        </p>
        <div class="grid grid-cols-6 gap-4">
          <div
            v-for="name in iconNames" :key="name"
            class="flex flex-col items-center gap-2 p-3 rounded-medium border border-border-gray2 bg-white100"
          >
            <Icon :name="name" :size="22" />
            <span class="text-detail text-gray700 text-center break-all">{{ name }}</span>
          </div>
        </div>
      </section>
    </main>
  </div>
</template>
