// src/Selector.vue
<script setup lang="ts">
// React Selector 동일 스펙 (커스텀 드롭다운 — 핵심 동작 포트)
import { computed, ref, watch, onMounted, onBeforeUnmount } from 'vue'
import Icon from './icons/Icon.vue'
import { dropdownPlacement, type DropdownPlacement } from './dropdownPlacement'

type OptionItem = string | { value: string; label: string }

const props = withDefaults(
  defineProps<{
    label?: string
    sublabel?: string
    placeholder?: string
    disabled?: boolean
    essential?: boolean
    modelValue?: string
    options?: OptionItem[]
    errorMessage?: string
    size?: 'medium' | 'large'
    fullWidth?: boolean
  }>(),
  { placeholder: '', disabled: false, essential: false, options: () => [], size: 'medium', fullWidth: false },
)
const emit = defineEmits<{ (e: 'update:modelValue', v: string): void }>()

const open = ref(false)
const root = ref<HTMLElement>()
const trigger = ref<HTMLButtonElement>()
const list = ref<HTMLElement>()
const placement = ref<DropdownPlacement>('bottom')

// 열리는 순간(페인트 전) 아래 공간을 재서 모자라면 위로 펼친다 — 하단 고정 푸터에 가려 스크롤해야 하는 문제
watch(
  open,
  (isOpen) => {
    if (isOpen && trigger.value && list.value) placement.value = dropdownPlacement(trigger.value, list.value.offsetHeight)
  },
  { flush: 'post' },
)

const optValue = (o: OptionItem) => (typeof o === 'string' ? o : o.value)
const optLabel = (o: OptionItem) => (typeof o === 'string' ? o : o.label)
const selectedLabel = computed(() => {
  const found = props.options.find((o) => optValue(o) === props.modelValue)
  return found ? optLabel(found) : ''
})

const boxClasses = computed(() => {
  const base = `w-full flex items-center justify-between gap-2 self-stretch border rounded-small cursor-pointer ${props.size === 'large' ? 'p-4' : 'px-4 py-3.5'}`
  if (props.disabled) return `${base} border-gray400 bg-bg-gray1 text-gray500 cursor-not-allowed`
  if (open.value) return `${base} border-sky bg-white100 text-gray800 text-body2`
  return `${base} border-gray400 bg-white100 ${selectedLabel.value ? 'text-gray800' : 'text-gray600'} text-body2`
})

function pick(o: OptionItem) {
  emit('update:modelValue', optValue(o))
  open.value = false
}
function onOutside(e: MouseEvent) {
  if (root.value && !root.value.contains(e.target as Node)) open.value = false
}
onMounted(() => document.addEventListener('mousedown', onOutside))
onBeforeUnmount(() => document.removeEventListener('mousedown', onOutside))
</script>

<template>
  <div ref="root" :class="`${fullWidth ? 'w-full' : 'w-[289px]'} relative flex flex-col items-start gap-3`">
    <div v-if="label || sublabel" class="w-full flex flex-col items-start gap-1 self-stretch">
      <label v-if="label" class="text-body1 font-semibold text-gray900">
        {{ label }}<span v-if="essential" class="text-sky"> *</span>
      </label>
      <span v-if="sublabel" class="text-body2 text-gray700">{{ sublabel }}</span>
    </div>
    <div class="relative w-full self-stretch">
      <button ref="trigger" type="button" :class="boxClasses" :disabled="disabled" @click="open = !open">
        <span class="truncate">{{ selectedLabel || placeholder }}</span>
        <Icon name="arrow-down" size="sm" color="gray800" :class="open ? 'rotate-180' : ''" class="transition-transform" />
      </button>
      <div
        v-if="open"
        ref="list"
        :class="placement === 'top' ? 'bottom-full mb-1' : 'top-full mt-1'"
        class="absolute left-0 right-0 z-50 max-h-[240px] overflow-y-auto rounded-medium border border-border-gray bg-white100 shadow-normal-normal p-1"
      >
        <div
          v-for="o in options"
          :key="optValue(o)"
          class="px-4 py-2.5 text-[14px] font-medium text-gray800 rounded-medium cursor-pointer transition-colors truncate"
          :class="optValue(o) === modelValue ? 'bg-bg-gray3 font-semibold text-gray900' : 'hover:bg-bg-gray3'"
          @click="pick(o)"
        >
          {{ optLabel(o) }}
        </div>
      </div>
    </div>
    <p v-if="errorMessage" class="text-detail leading-4 text-red">{{ errorMessage }}</p>
  </div>
</template>

// src/inputs/Selector.tsx
import React, { useState, useEffect, useLayoutEffect, useRef } from 'react';
import Icon from '../display/Icon';
import { dropdownPlacement, type DropdownPlacement } from './dropdownPlacement';

type OptionItem = string | { label: string; value: string };

interface SelectorProps {
  label?: string;
  sublabel?: string;
  placeholder?: string;
  disabled?: boolean;
  essential?: boolean;
  lefticon?: string;
  value?: string;
  options?: OptionItem[];
  onChange?: (value: string) => void;
  errorMessage?: string;
  size?: 'medium' | 'large';
  className?: string;
  'data-testid'?: string;
}

function getOptionValue(opt: OptionItem): string {
  return typeof opt === 'string' ? opt : opt.value;
}

function getOptionLabel(opt: OptionItem): string {
  return typeof opt === 'string' ? opt : opt.label;
}

function findLabelByValue(options: OptionItem[], value: string): string {
  const found = options.find((opt) => getOptionValue(opt) === value);
  return found ? getOptionLabel(found) : value;
}

const Selector: React.FC<SelectorProps> = ({
  label,
  sublabel,
  placeholder = '',
  disabled = false,
  essential = false,
  lefticon,
  options,
  value,
  onChange,
  errorMessage: externalErrorMessage,
  size = 'medium',
  className,
  'data-testid': testId,
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [selectedValue, setSelectedValue] = useState(value || '');
  const [isFocused, setIsFocused] = useState(false);
  const [internalState, setInternalState] = useState<'normal' | 'filled' | 'error' | 'disabled'>('normal');
  const [internalError, setInternalError] = useState('');
  const [placement, setPlacement] = useState<DropdownPlacement>('bottom');
  const containerRef = useRef<HTMLDivElement>(null);
  const triggerRef = useRef<HTMLDivElement>(null);
  const listRef = useRef<HTMLUListElement>(null);

  // 열리는 순간(페인트 전) 아래 공간을 재서 모자라면 위로 펼친다 — 하단 고정 푸터에 가려 스크롤해야 하는 문제
  useLayoutEffect(() => {
    if (!isOpen || !triggerRef.current || !listRef.current) return;
    setPlacement(dropdownPlacement(triggerRef.current, listRef.current.offsetHeight));
  }, [isOpen]);

  const selectorId = useRef(`selector-${Math.random().toString(36).substr(2, 9)}`).current;

  const validateSelection = (val: string) => {
    if (essential && !val) {
      setInternalError('옵션을 선택하세요');
      setInternalState('error');
    } else {
      setInternalError('');
      setInternalState(val ? 'filled' : 'normal');
    }
  };

  const handleBlur = (e: React.FocusEvent<HTMLDivElement>) => {
    if (!e.currentTarget.contains(e.relatedTarget as Node)) {
      setIsOpen(false);
      setIsFocused(false);
      validateSelection(selectedValue);
    }
  };

  const handleFocus = () => {
    if (!disabled) {
      setIsFocused(true);
    }
  };

  const handleToggle = () => {
    if (!disabled) {
      setIsOpen(!isOpen);
    }
  };

  const handleSelect = (optionValue: string) => {
    setSelectedValue(optionValue);
    setIsOpen(false);
    validateSelection(optionValue);
    onChange?.(optionValue);
  };

  useEffect(() => {
    if (value !== undefined) {
      setSelectedValue(value);
    }
  }, [value]);

  useEffect(() => {
    if (disabled) {
      setInternalState('disabled');
      setInternalError('');
    } else if (externalErrorMessage) {
      setInternalState('error');
      setInternalError(externalErrorMessage);
    } else {
      validateSelection(selectedValue);
    }
  }, [disabled, essential, selectedValue, externalErrorMessage]);

  const effectiveErrorMessage = externalErrorMessage || internalError;

  const displayLabel = selectedValue && options
    ? findLabelByValue(options, selectedValue)
    : '';

  const getContainerClasses = () => {
    if (size === 'large') return 'p-4';
    return 'px-4 py-3';
  };

  const getSelectorClasses = () => {
    const heightClass = size === 'medium' ? 'h-[42px]' : 'h-[50px]';
    const baseClasses = `w-full ${heightClass} flex items-center gap-2 rounded-small border outline-none cursor-pointer ${getContainerClasses()}`;

    if (internalState === 'disabled') {
      return `${baseClasses} border-gray400 bg-bg_gray1 text-gray600 cursor-not-allowed`;
    } else if (internalState === 'error') {
      return `${baseClasses} border-red bg-white text-gray800`;
    } else if (isFocused || isOpen) {
      return `${baseClasses} border-sky bg-white text-gray800`;
    } else {
      return `${baseClasses} border-gray400 bg-white ${selectedValue ? 'text-gray800' : 'text-gray600'}`;
    }
  };

  const getTextClasses = () => {
    if (internalState === 'disabled') return 'text-gray500';
    if (internalState === 'filled') return 'text-gray800 font-semibold';
    return 'text-gray600 font-medium';
  };

  return (
    <div className={`w-full h-auto flex flex-col items-start gap-3 ${className ?? ''}`}>
      {/* Label */}
      {(label || sublabel) && (
        <div className="w-full h-auto flex flex-col items-start gap-1 self-stretch">
          {label && (
            <label
              htmlFor={internalState !== 'disabled' ? selectorId : undefined}
              className="w-auto h-auto text-body1 font-semibold text-gray900 font-pretendard"
            >
              {label}
              {essential && <span className="text-sky"> *</span>}
            </label>
          )}
          {sublabel && (
            <span className="text-body2 font-regular text-gray700 font-pretendard">
              {sublabel}
            </span>
          )}
        </div>
      )}
      {/* Wrap */}
      <div
        ref={containerRef}
        className="w-full h-auto flex flex-col items-start gap-2 self-stretch relative"
        onBlur={handleBlur}
        onFocus={handleFocus}
      >
        <div
          ref={triggerRef}
          id={selectorId}
          className={getSelectorClasses()}
          onClick={handleToggle}
          tabIndex={internalState === 'disabled' ? -1 : 0}
          aria-expanded={isOpen}
          aria-disabled={internalState === 'disabled'}
          aria-invalid={internalState === 'error'}
          aria-describedby={internalState === 'error' && effectiveErrorMessage ? `${selectorId}-error` : undefined}
          aria-label={displayLabel || placeholder}
          data-testid={testId}
        >
          {lefticon && (
            <Icon
              name={lefticon}
              className="w-[18px] h-[18px] flex-shrink-0"
            />
          )}
          <span className={`flex-1 text-body2 truncate font-medium font-pretendard ${getTextClasses()}`}>
            {displayLabel || placeholder}
          </span>
          <Icon
            name="arrow-down"
            className="w-[18px] h-[18px] flex-shrink-0"
          />
        </div>
        {isOpen && options && (
          <ul
            ref={listRef}
            className={`absolute w-full p-1.5 ${placement === 'top' ? 'bottom-[100%] mb-2' : 'top-[100%] mt-2'} bg-white rounded-[12px] shadow-[0px_2px_28px_0px_rgba(0,0,0,0.08)] max-h-60 overflow-y-auto z-[1000] [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-thumb]:bg-gray-200 [&::-webkit-scrollbar-thumb]:rounded-full`}
          >
            {options.map((option) => {
              const optValue = getOptionValue(option);
              const optLabel = getOptionLabel(option);
              return (
                <li
                  key={optValue}
                  className={`px-4 py-2.5 text-[14px] font-medium text-gray800 rounded-[8px] cursor-pointer transition-colors truncate ${
                    optValue === selectedValue ? 'bg-bg_gray3 font-semibold text-gray900' : 'hover:bg-bg_gray3'
                  }`}
                  onClick={(e) => {
                    e.stopPropagation();
                    handleSelect(optValue);
                  }}
                  onMouseDown={(e) => e.preventDefault()}
                >
                  {optLabel}
                </li>
              );
            })}
          </ul>
        )}
      </div>
      {/* Error Message */}
      {internalState === 'error' && effectiveErrorMessage && (
        <p
          id={`${selectorId}-error`}
          className="text-detail font-regular leading-[16px] text-red font-pretendard"
        >
          {effectiveErrorMessage}
        </p>
      )}
    </div>
  );
};

export default Selector;
