// src/TextInput.vue
<script setup lang="ts">
// React TextInput(확장판) 동일 스펙 — controlled·type·fullWidth 지원
import { computed, ref, watch } from 'vue'

type State = 'normal' | 'filled' | 'only_view' | 'error'

const props = withDefaults(
  defineProps<{
    label?: string
    sublabel?: string
    placeholder?: string
    disabled?: boolean
    essential?: boolean
    modelValue?: string
    type?: string
    errorMessage?: string
    state?: State
    size?: 'medium' | 'large'
    fullWidth?: boolean
    maxLength?: number
  }>(),
  { placeholder: '', disabled: false, essential: false, type: 'text', size: 'medium', fullWidth: false },
)

const emit = defineEmits<{ (e: 'update:modelValue', v: string): void }>()

const inner = ref('')
const focused = ref(false)
const current = computed(() => (props.modelValue !== undefined ? props.modelValue : inner.value))

const internalState = ref<State>('normal')
watch(
  [() => props.state, focused, current],
  () => {
    if (props.state !== undefined) internalState.value = props.state
    else if (!focused.value) internalState.value = current.value ? 'filled' : 'normal'
  },
  { immediate: true },
)

const interactionDisabled = computed(() => internalState.value === 'only_view' || props.disabled)

const boxClasses = computed(() => {
  const base = `w-full h-auto flex items-center gap-2 self-stretch border rounded-small ${props.size === 'large' ? 'p-4' : 'px-4 py-3.5'}`
  if (props.disabled) return `${base} border-gray400 bg-bg-gray1 text-gray500 text-body2 placeholder:text-gray500 cursor-not-allowed`
  if (focused.value && internalState.value !== 'only_view' && internalState.value !== 'error')
    return `${base} border-sky bg-white100 text-gray800 text-body2 placeholder:text-gray600`
  switch (internalState.value) {
    case 'filled': return `${base} border-gray400 bg-white100 text-gray800 text-body2 placeholder:text-gray600`
    case 'only_view': return `${base} border-gray400 bg-bg-gray1 text-gray800 text-body2 cursor-default`
    case 'error': return `${base} border-red bg-white100 text-gray800 text-body2 placeholder:text-gray600`
    default: return `${base} border-gray400 bg-white100 text-gray600 text-body2 placeholder:text-gray600`
  }
})

function onInput(e: Event) {
  const v = (e.target as HTMLInputElement).value
  if (props.modelValue === undefined) inner.value = v
  emit('update:modelValue', v)
}
</script>

<template>
  <div :class="`${fullWidth ? 'w-full' : 'w-[289px]'} h-auto flex flex-col items-start gap-3`">
    <div v-if="label || sublabel" class="w-full h-auto flex flex-col items-start gap-1 self-stretch">
      <label v-if="label" class="text-body1 font-semibold text-gray900">
        {{ label }}<span v-if="essential" class="text-sky"> *</span>
      </label>
      <span v-if="sublabel" class="text-body2 text-gray700">{{ sublabel }}</span>
    </div>
    <div class="w-full h-auto flex flex-col items-start gap-2 self-stretch">
      <div :class="boxClasses">
        <input
          :type="type"
          :placeholder="placeholder"
          :disabled="interactionDisabled"
          :readonly="internalState === 'only_view'"
          :value="current"
          :maxlength="maxLength"
          class="w-full h-auto max-h-[18px] flex-1 outline-none bg-transparent"
          @input="onInput"
          @focus="!interactionDisabled && (focused = true)"
          @blur="focused = false"
        />
      </div>
      <p v-if="internalState === 'error' && errorMessage" class="text-detail leading-4 text-red">{{ errorMessage }}</p>
    </div>
  </div>
</template>

// src/inputs/TextInput.tsx
import React, { useState, useEffect } from 'react';
import Icon from '../display/Icon';

type IconName = 'search' | 'clear' | 'eye';
type TextInputState = 'normal' | 'filled' | 'only_view' | 'error';

interface TextInputProps {
  label?: string;
  sublabel?: string;
  placeholder?: string;
  disabled?: boolean;
  essential?: boolean;
  lefticon?: IconName;
  righticon?: IconName;
  onChange?: (value: string) => void;
  errorMessage?: string;
  state?: TextInputState;
  size?: 'medium' | 'large';
}

const TextInput: React.FC<TextInputProps> = ({
  label,
  sublabel,
  placeholder = '',
  disabled = false,
  essential = false,
  lefticon,
  righticon,
  onChange,
  errorMessage,
  state: propState,
  size = 'medium',
}) => {
  const [inputValue, setInputValue] = useState('');
  const [isFocused, setIsFocused] = useState(false);
  const [internalState, setInternalState] = useState<TextInputState>('normal');

  // Generate a unique inputId, using label if provided, otherwise a generic fallback
  const inputId = label ? `text-input-${label.replace(/\s/g, '-')}` : `text-input-${Math.random().toString(36).substring(2, 9)}`;

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setInputValue(value);
    onChange?.(value);
  };

  const handleFocus = () => {
    setIsFocused(true);
  };

  const handleBlur = () => {
    setIsFocused(false);
  };

  useEffect(() => {
    if (propState !== undefined) {
      setInternalState(propState);
    } else {
      if (!isFocused) {
        setInternalState(inputValue ? 'filled' : 'normal');
      }
    }
  }, [propState, isFocused, inputValue]);

  const getInputClasses = (): string => {
    const baseClasses = `w-full h-auto flex items-center gap-[8px] self-stretch border rounded-small ${getContainerClasses()}`;

    if (disabled) {
      return `${baseClasses} border-gray400 bg-bg_gray1 text-gray500 text-body2 font-regular placeholder:text-gray500 cursor-not-allowed`;
    }

    if (isFocused && internalState !== 'only_view' && internalState !== 'error') {
      return `${baseClasses} border-sky bg-white100 text-gray800 text-body2 font-regular placeholder:text-gray600`;
    }

    switch (internalState) {
      case 'normal':
        return `${baseClasses} border-gray400 bg-white100 text-gray600 text-body2 font-regular placeholder:text-gray600`;
      case 'filled':
        return `${baseClasses} border-gray400 bg-white100 text-gray800 text-body2 font-regular placeholder:text-gray600`;
      case 'only_view':
        return `${baseClasses} border-gray400 bg-bg_gray1 text-gray800 text-body2 font-regular cursor-default`;
      case 'error':
        return `${baseClasses} border-red bg-white100 text-gray800 text-body2 font-regular placeholder:text-gray600`;
      default:
        return `${baseClasses} border-gray400 bg-white100 text-gray600 text-body2 font-regular placeholder:text-gray600`;
    }
  };

  const getContainerClasses = () => {
    if (size === 'large') {
      return `p-[16px]`;
    }
    return `px-[16px] py-[14px]`;
  };

  const isInteractionDisabled = internalState === 'only_view' || disabled;

  return (
    <div className="w-[289px] h-auto flex flex-col items-start gap-[12px]">
      {(label || sublabel) && (
        <div className="w-full h-auto flex flex-col items-start gap-[4px] self-stretch">
          {label && (
            <label
              htmlFor={!isInteractionDisabled ? inputId : undefined}
              className="text-body1 font-semibold text-gray900 font-pretendard"
            >
              {label}
              {essential && <span className="text-sky"> *</span>}
            </label>
          )}
          {sublabel && (
            <span className="text-body2 font-regular text-gray700 font-pretendard">
              {sublabel}
            </span>
          )}
        </div>
      )}

      <div className="w-full h-auto flex flex-col items-start gap-[8px] self-stretch">
        <div className={getInputClasses()}>
          {lefticon && (
            <Icon
              name={lefticon}
              className='flex-shrink-0 w-[18px] h-[18px]'
            />
          )}
          <input
            id={inputId}
            type="text"
            placeholder={placeholder}
            disabled={isInteractionDisabled}
            value={inputValue}
            onChange={handleChange}
            onFocus={!isInteractionDisabled ? handleFocus : undefined}
            onBlur={!isInteractionDisabled ? handleBlur : undefined}
            className="w-full h-auto max-h-[18px] flex-1 outline-none bg-transparent"
            aria-invalid={internalState === 'error'}
            aria-describedby={internalState === 'error' && errorMessage ? `${inputId}-error` : undefined}
            readOnly={internalState === 'only_view'}
          />
          {righticon && (
            <Icon
              name={righticon}
              className='flex-shrink-0 w-[18px] h-[18px]'
            />
          )}
        </div>

        {internalState === 'error' && errorMessage && (
          <p
            id={`${inputId}-error`}
            className="text-detail font-regular leading-[16px] text-red font-pretendard"
          >
            {errorMessage}
          </p>
        )}
      </div>
    </div>
  );
};

export default TextInput;
