// src/HistoryEntry.vue
<script setup lang="ts">
// React HistoryEntry 와 동일 스펙 — 경력/학력 엔트리. default slot 의 ActivityDetail 사이에 구분선은 소비자가 <hr> 로 넣거나 divider 슬롯 없이 gap 으로 처리
import Icon from './icons/Icon.vue'
withDefaults(defineProps<{ type?: 'career' | 'education'; name: string; role: string; period: string; logoUrl?: string }>(), { type: 'career' })
</script>

<template>
  <div class="flex items-start gap-4">
    <div class="shrink-0 w-12 h-12 flex items-center justify-center rounded-medium bg-bg-gray1 border border-border-gray overflow-hidden">
      <img v-if="logoUrl" :src="logoUrl" alt="" class="w-full h-full object-cover" />
      <Icon v-else :name="type === 'career' ? 'company' : 'graduation_hat'" :size="24" color="#727180" />
    </div>
    <div class="min-w-0 flex-1 flex flex-col gap-6 [&>hr]:border-0 [&>hr]:border-t [&>hr]:border-border-gray">
      <div class="flex flex-col gap-1">
        <div class="flex items-center justify-between gap-3">
          <span class="text-subtitle3 font-bold text-gray900 truncate">{{ name }}</span>
          <span class="shrink-0 text-body2 text-gray600">{{ period }}</span>
        </div>
        <span class="text-body1 font-medium text-gray700">{{ role }}</span>
      </div>
      <slot />
    </div>
  </div>
</template>

// src/display/HistoryEntry.tsx
import React from 'react';
import Icon from './Icon';

// 경력/학력 엔트리 (Figma "experience-entry") — 로고 칸 + 기업명/학교명 · 기간 · 직무/학과, 아래에 활동 상세(children)
interface HistoryEntryProps {
  type?: 'career' | 'education';
  /** 기업명 / 학교명 */
  name: string;
  /** 직무 / 학과 */
  role?: string;
  /** 예: "2024. 05 - 2026. 01 · 1년 9월" */
  period?: string;
  logoUrl?: string;
  /** ActivityDetail 목록 — 항목 사이 구분선 자동 */
  children?: React.ReactNode;
  className?: string;
}

export function HistoryEntry({ type = 'career', name, role, period, logoUrl, children, className = '' }: HistoryEntryProps) {
  const items = React.Children.toArray(children);
  return (
    <div className={`flex items-start gap-4 ${className}`.trim()}>
      <div className="shrink-0 w-12 h-12 flex items-center justify-center rounded-medium bg-bg_gray1 border border-border_gray overflow-hidden">
        {logoUrl ? (
          <img src={logoUrl} alt="" className="w-full h-full object-cover" />
        ) : (
          <Icon name={type === 'career' ? 'company' : 'graduation_hat'} size={24} color="#727180" />
        )}
      </div>
      <div className="min-w-0 flex-1 flex flex-col gap-6">
        <div className="flex flex-col gap-1">
          <div className="flex items-center justify-between gap-3">
            <span className="text-subtitle3 font-bold text-gray900 truncate">{name}</span>
            {period && <span className="shrink-0 text-body2 text-gray600">{period}</span>}
          </div>
          {role && <span className="text-body1 font-medium text-gray700">{role}</span>}
        </div>
        {items.map((child, i) => (
          <React.Fragment key={i}>
            {i > 0 && <hr className="border-0 border-t border-border_gray" />}
            {child}
          </React.Fragment>
        ))}
      </div>
    </div>
  );
}

export default HistoryEntry;
