// src/display/Badge.tsx
import React from 'react';

// 사이드바 메뉴 등에서 쓰는 상태 배지 (careernote-web SidebarNavItem 인라인 span 이관)
export type BadgeVariant = 'Soon' | 'New' | 'Beta';

interface BadgeProps {
  variant: BadgeVariant;
  children?: React.ReactNode;
  className?: string;
  'data-testid'?: string;
}

const variantStyles: Record<BadgeVariant, string> = {
  Soon: 'bg-green10 text-green100',
  New: 'bg-blue200 text-white',
  Beta: 'bg-gray900 text-white',
};

export function Badge({ variant, children, className = '', 'data-testid': testId }: BadgeProps) {
  return (
    <span
      data-testid={testId}
      className={`text-xs leading-4 font-normal rounded w-10 text-center py-0.5 shrink-0 ${variantStyles[variant]} ${className}`.trim()}
    >
      {children ?? variant}
    </span>
  );
}

export default Badge;

// packages/vue/src/Badge.vue
<script setup lang="ts">
// React Badge 와 동일 스펙 (Soon/New/Beta 상태 배지)
import { computed } from 'vue'

const props = defineProps<{ variant: 'Soon' | 'New' | 'Beta' }>()

const variantStyles = {
  Soon: 'bg-green10 text-green100',
  New: 'bg-blue200 text-white',
  Beta: 'bg-gray900 text-white',
}

const classes = computed(
  () => `text-xs leading-4 font-normal rounded w-10 text-center py-0.5 shrink-0 inline-block ${variantStyles[props.variant]}`,
)
</script>

<template>
  <span :class="classes"><slot>{{ variant }}</slot></span>
</template>
