// src/display/TalentpoolCard.tsx
import React from 'react';
import { CandidateProfile, UpdatedChip } from './CandidateProfile';
import { CandidateHistory, type EducationEntry } from './CandidateHistory';
import { ExperienceItem, type ExperienceEntry } from './ExperienceItem';
import type { CareerEntry } from './CareerTooltip';

// 인재풀 카드 (Figma "Talentpool_card") — 지원 상태 없음, 업데이트 칩, 대표 활동 1개, 메모 없음
interface TalentpoolCardProps {
  name: string;
  imageUrl?: string;
  careerLabel: string;
  job: string;
  /** 마지막 프로필 업데이트로부터 경과 일수 — 30일 이내 purple, 이후 black */
  updatedDaysAgo: number;
  /** 프로필 전체 한줄 요약 */
  aiSummary: string;
  careers: CareerEntry[];
  education?: EducationEntry;
  /** 대표 활동 1개 */
  experience?: ExperienceEntry;
  onExperienceClick?: (exp: ExperienceEntry) => void;
  className?: string;
}

export function TalentpoolCard({
  name,
  imageUrl,
  careerLabel,
  job,
  updatedDaysAgo,
  aiSummary,
  careers,
  education,
  experience,
  onExperienceClick,
  className = '',
}: TalentpoolCardProps) {
  return (
    <div
      className={`w-[500px] max-w-full flex flex-col gap-4 p-5 bg-white100 border border-border_gray rounded-xlarge shadow-wide-light ${className}`.trim()}
    >
      <div className="flex flex-col gap-4">
        <CandidateProfile
          name={name}
          imageUrl={imageUrl}
          careerLabel={careerLabel}
          job={job}
          badge={<UpdatedChip daysAgo={updatedDaysAgo} />}
        />
        <hr className="border-0 border-t border-border_gray" />
      </div>
      <div className="flex flex-col gap-[17px]">
        <CandidateHistory aiSummary={aiSummary} careers={careers} education={education} />
        {experience && (
          <ExperienceItem {...experience} onClick={onExperienceClick ? () => onExperienceClick(experience) : undefined} />
        )}
      </div>
    </div>
  );
}

export default TalentpoolCard;

// packages/vue/src/TalentpoolCard.vue
<script setup lang="ts">
// React TalentpoolCard 와 동일 스펙 — 인재풀 카드 (업데이트 칩, 대표 활동 1개, 메모 없음)
import CandidateProfile from './CandidateProfile.vue'
import UpdatedChip from './UpdatedChip.vue'
import CandidateHistory from './CandidateHistory.vue'
import ExperienceItem from './ExperienceItem.vue'
import type { ExperienceEntry } from './ExperienceItem.vue'
import type { CareerEntry } from './CareerTooltip.vue'
import type { EducationEntry } from './candidate-types'

defineProps<{
  name: string
  imageUrl?: string
  careerLabel: string
  job: string
  /** 마지막 업데이트 경과 일수 — 30일 이내 purple, 이후 black */
  updatedDaysAgo: number
  aiSummary: string
  careers: CareerEntry[]
  education?: EducationEntry
  experience?: ExperienceEntry
}>()

const emit = defineEmits<{ (e: 'experience-click', exp: ExperienceEntry): void }>()
</script>

<template>
  <div class="w-[500px] max-w-full flex flex-col gap-4 p-5 bg-white100 border border-border-gray rounded-xlarge shadow-wide-light">
    <div class="flex flex-col gap-4">
      <CandidateProfile :name="name" :image-url="imageUrl" :career-label="careerLabel" :job="job">
        <template #badge><UpdatedChip :days-ago="updatedDaysAgo" /></template>
      </CandidateProfile>
      <hr class="border-0 border-t border-border-gray" />
    </div>
    <div class="flex flex-col gap-[17px]">
      <CandidateHistory :ai-summary="aiSummary" :careers="careers" :education="education" />
      <ExperienceItem v-if="experience" v-bind="experience" clickable @click="emit('experience-click', experience)" />
    </div>
  </div>
</template>
