// src/ProgressBarItem.vue
<script setup lang="ts">
// React ProgressBarItem 동일 스펙 (스텝 아이콘 + 라벨)
import Icon from './icons/Icon.vue'

withDefaults(defineProps<{ status: 'complete' | 'waiting' | 'editing'; text: string; number?: number }>(), {
  number: 1,
})
</script>

<template>
  <div class="inline-flex items-center gap-2">
    <Icon v-if="status === 'complete'" name="check" size="sm" color="skyblue" />
    <Icon v-else :name="`number_${number}`" size="sm" :color="status === 'editing' ? 'skyblue' : 'gray800'" />
    <span class="text-body1 font-semibold" :class="status === 'waiting' ? 'text-gray800' : 'text-sky'">{{ text }}</span>
  </div>
</template>

// src/navigation/ProgressBarItem.tsx
import React from 'react';
import Icon from '../display/Icon';

type Status = 'complete' | 'waiting' | 'editing';

interface ProgressBarItemProps {
  status: Status; // complete | waiting | editing
  text: string;
  number?: number; // 1~9 숫자 지정
  className?: string;
}

const ProgressBarItem: React.FC<ProgressBarItemProps> = ({ status, text, number = 1, className = '' }) => {
  const renderIcon = () => {
    switch (status) {
      case 'complete':
        return <Icon name="check" size="sm" color="skyblue" />;
      case 'editing':
        return <Icon name={`number_${number}` as any} size="sm" color="skyblue" />;
      case 'waiting':
      default:
        return <Icon name={`number_${number}` as any} size="sm" color="gray800" />;
    }
  };

  const textClass = status === 'waiting' ? 'text-gray800' : 'text-sky';

  return (
    <div className={`inline-flex items-center gap-[8px] ${className}`}>
      {renderIcon()}
      <span className={`text-body1 font-semibold ${textClass}`}>{text}</span>
    </div>
  );
};

export default ProgressBarItem;
