// packages/react/src/display/CandidateHeader.tsx
import React from 'react';
import { ProfileHero } from './ProfileHero';
import { CandidateIntro, type ContactEntry } from './CandidateIntro';

// 상세페이지 프로필 헤더 — ProfileHero + CandidateIntro 가로 조립
export interface CandidateHeaderData {
  name: string;
  role: string;
  imageUrl?: string;
  slogan?: string;
  introduction?: string;
  contacts?: ContactEntry[];
}

interface CandidateHeaderProps extends CandidateHeaderData {
  onEdit?: () => void;
  className?: string;
}

export function CandidateHeader({ name, role, imageUrl, onEdit, slogan, introduction, contacts, className = '' }: CandidateHeaderProps) {
  return (
    <div className={`flex items-stretch gap-5 ${className}`.trim()}>
      <ProfileHero name={name} role={role} imageUrl={imageUrl} onEdit={onEdit} />
      <CandidateIntro slogan={slogan} introduction={introduction} contacts={contacts} />
    </div>
  );
}

export default CandidateHeader;

// src/CandidateHeader.vue
<script setup lang="ts">
// React CandidateHeader 와 동일 스펙 — ProfileHero + CandidateIntro
import ProfileHero from './ProfileHero.vue'
import CandidateIntro from './CandidateIntro.vue'
import type { ContactEntry } from './CandidateIntro.vue'
export interface CandidateHeaderData { name: string; role: string; imageUrl?: string; slogan?: string; introduction?: string; contacts?: ContactEntry[] }
withDefaults(defineProps<CandidateHeaderData & { editable?: boolean }>(), { editable: false })
const emit = defineEmits<{ (e: 'edit'): void }>()
</script>

<template>
  <div class="flex items-stretch gap-5">
    <ProfileHero :name="name" :role="role" :image-url="imageUrl" :editable="editable" @edit="emit('edit')" />
    <CandidateIntro :slogan="slogan" :introduction="introduction" :contacts="contacts" />
  </div>
</template>
